"use client";

import Link from "next/link";
import Image from "next/image";
import { useQuery } from "convex/react";
import { api } from "@convex/_generated/api";
import { ArrowRight, CalendarDays, Clock3, Library, MapPin, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useLanguage } from "@/context/LanguageContext";
import { DEFAULT_ARTICLES } from "@/lib/articles-data";

const milestones=[{year:"1924",title:"The beginning",body:"The institutional foundation of the movement is laid."},{year:"1927",title:"Mahad Satyagraha",body:"A defining stand for dignity, access, and human rights."},{year:"1956",title:"A moral turn",body:"Babasaheb leads a mass conversion to Buddhism at Deekshabhoomi."},{year:"Today",title:"The work continues",body:"SSD carries the questions of equality into a new generation."}];
const stats=[["100+","years of service"],["10K+","members across India"],["500+","programs and events"],["Pan India","a growing network"]];

export default function HomePage(){
 const {language}=useLanguage(); const articlesQuery=useQuery(api.articles?.getFeatured as any,{limit:3}); const events=useQuery(api.events?.list as any,{status:"upcoming",limit:3}); const articles=articlesQuery?.length?articlesQuery:DEFAULT_ARTICLES.slice(0,3);
 return <div className="bg-background">
  <section className="relative isolate overflow-hidden bg-blue-deep text-paper"><div className="absolute inset-0 opacity-25"><Image src="/images/mahad-satyagraha.jpg" alt="Archival texture" fill priority className="object-cover" sizes="100vw" /></div><div className="absolute inset-0 bg-blue-deep/80" /><div className="container relative grid min-h-[720px] items-center gap-12 pb-16 pt-32 lg:grid-cols-[1.05fr_.95fr] lg:pb-20"><div className="animate-rise max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-saffron">Samta Sainik Dal Delhi</p><h1 className="mt-5 font-serif text-5xl leading-[1.02] sm:text-7xl">Knowledge is the first step toward liberation.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-paper/75">From the Mahad Satyagraha to the Constitution of India — explore the history, ideology, and ongoing fight for social justice that built Samata Sainik Dal.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-full bg-saffron px-7 text-paper hover:bg-saffron/90"><Link href="/history">Explore our history <ArrowRight data-icon="inline-end" /></Link></Button><Button asChild size="lg" variant="outline" className="rounded-full border-paper/40 bg-transparent text-paper hover:bg-paper/10 hover:text-paper"><Link href="/join">Join the movement</Link></Button></div></div><figure className="animate-rise relative mx-auto w-full max-w-sm lg:mr-8" style={{animationDelay:"120ms"}}><div className="absolute -inset-4 rounded-[2rem] border border-saffron/60" /><div className="relative aspect-[4/5] overflow-hidden rounded-xl bg-paper-dim"><Image src="/images/ambedkar-portrait.jpg" alt="Portrait of Dr. B.R. Ambedkar" fill className="object-cover object-top grayscale" sizes="(max-width:1024px) 80vw, 35vw" /></div><figcaption className="mt-4 border-l-2 border-saffron pl-4 text-sm text-paper/70">Dr. B.R. Ambedkar<br/><span className="text-paper/45">Founder of the movement</span></figcaption></figure></div><div className="container relative grid grid-cols-2 border-t border-paper/20 py-8 sm:grid-cols-4">{stats.map(([value,label])=><div key={label} className="border-r border-paper/15 px-4 first:pl-0 last:border-0"><p className="font-serif text-3xl text-saffron">{value}</p><p className="mt-1 text-xs uppercase tracking-wider text-paper/55">{label}</p></div>)}</div></section>
  <section className="container grid gap-12 py-20 sm:py-28 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden rounded-xl border-t-4 border-saffron bg-paper-dim"><Image src="/images/buddha-statue.jpg" alt="Buddha statue representing Dhamma and compassion" fill className="object-cover object-center" sizes="(max-width:1024px) 90vw, 40vw" /></div><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-saffron">Why SSD Delhi exists</p><h2 className="mt-4 font-serif text-4xl leading-tight text-blue-deep sm:text-6xl">A history that still asks something of us.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Samta Sainik Dal is a people&apos;s movement for social transformation. We preserve the ideas, stories, and practices that help communities challenge caste and build a more equal society.</p><div className="mt-8 flex flex-wrap gap-3">{["Liberty","Equality","Fraternity"].map(x=><Badge key={x} variant="outline" className="rounded-full border-blue/40 px-4 py-2 text-blue">{x}</Badge>)}</div><Button asChild variant="link" className="mt-8 px-0 text-blue hover:text-saffron"><Link href="/about">Learn about our organisation <ArrowRight data-icon="inline-end" /></Link></Button></div></section>
  <section className="bg-paper-dim py-20 sm:py-28"><div className="container"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-saffron">From the archive</p><h2 className="mt-3 font-serif text-4xl text-blue-deep sm:text-5xl">Ideas worth carrying forward</h2></div><Button asChild variant="outline" className="w-fit rounded-full border-blue text-blue hover:bg-blue hover:text-paper"><Link href="/articles">View all articles <ArrowRight data-icon="inline-end" /></Link></Button></div><div className="grid gap-5 md:grid-cols-3">{!articles?[1,2,3].map(x=><Skeleton key={x} className="h-64"/>):articles.map((article:any)=><Link key={article.slug||article._id} href={`/articles/${article.slug}`} className="group"><Card className="h-full rounded-xl border-border bg-background shadow-none transition-transform group-hover:-translate-y-1"><CardHeader><Badge variant="outline" className="w-fit rounded-full border-saffron/50 text-saffron">{article.category}</Badge><CardTitle className="font-serif text-2xl text-blue-deep group-hover:text-saffron">{article.title}</CardTitle><CardDescription className="line-clamp-3 leading-6">{article.excerpt}</CardDescription></CardHeader><CardContent><span className="text-sm font-medium text-blue">Read story <ArrowRight className="ml-1 inline size-4" /></span></CardContent></Card></Link>)}</div></div></section>
  <section className="container py-20 sm:py-28"><div className="mb-12 flex items-end justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-saffron">Be part of the work</p><h2 className="mt-3 font-serif text-4xl text-blue-deep sm:text-5xl">Gather, learn, act.</h2></div><Link href="/events" className="hidden text-sm font-medium text-blue sm:block">Full calendar <ArrowRight className="ml-1 inline size-4" /></Link></div><div className="grid gap-5 md:grid-cols-3">{events===undefined?[1,2,3].map(x=><Skeleton key={x} className="h-56"/>):events.map((event:any)=><Link key={event._id} href={`/events/${event.slug}`} className="group"><Card className="h-full rounded-xl shadow-none transition-colors group-hover:border-saffron"><CardHeader><p className="flex items-center gap-2 text-sm text-saffron"><CalendarDays className="size-4"/>{new Date(event.startDate).toLocaleDateString(language==="hi"?"hi-IN":"en-IN",{month:"short",day:"numeric",year:"numeric"})}</p><CardTitle className="font-serif text-2xl text-blue-deep group-hover:text-saffron">{event.title}</CardTitle><CardDescription className="flex items-center gap-2"><MapPin className="size-4"/>{event.venue}, {event.city}</CardDescription></CardHeader><CardContent><span className="text-sm text-muted-foreground"><Clock3 className="mr-1 inline size-4"/> Community gathering</span></CardContent></Card></Link>)}</div></section>
  <section className="bg-blue-deep py-20 text-paper sm:py-28"><div className="container"><p className="text-sm font-semibold uppercase tracking-[.18em] text-saffron">A century in motion</p><h2 className="mt-3 max-w-2xl font-serif text-4xl sm:text-6xl">The past is a practice.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-xl bg-paper/20 sm:grid-cols-2 lg:grid-cols-4">{milestones.map(x=><div key={x.year} className="bg-blue-deep p-7"><p className="font-serif text-4xl text-saffron">{x.year}</p><h3 className="mt-6 text-lg font-semibold">{x.title}</h3><p className="mt-3 text-sm leading-6 text-paper/60">{x.body}</p></div>)}</div><Button asChild variant="outline" className="mt-10 rounded-full border-paper/40 bg-transparent text-paper hover:bg-paper/10 hover:text-paper"><Link href="/history">Walk through the timeline <ArrowRight data-icon="inline-end" /></Link></Button></div></section>
  <section className="bg-saffron py-16 text-blue-deep sm:py-20"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.18em]">The next chapter is yours</p><h2 className="mt-3 max-w-2xl font-serif text-4xl sm:text-5xl">Stand for dignity. Build solidarity.</h2></div><Button asChild size="lg" className="rounded-full bg-blue-deep px-8 text-paper hover:bg-blue"><Link href="/join">Become a member <ArrowRight data-icon="inline-end"/></Link></Button></div></section>
 </div>;
}
