import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Mail, MapPin, Users } from "lucide-react";
import { getOfficerBySlug } from "@/lib/supabase-rest";
import { OfficerAvatar, SocialLinks } from "@/components/officer-profile-card";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const officer = await getOfficerBySlug((await params).slug); return { title: officer ? `${officer.name} | National Executive` : "Officer Profile | SSD Delhi", description: officer ? `${officer.designation}, ${officer.state}. Official profile of Samta Sainik Dal.` : "National officer profile." }; }

export default async function OfficerPage({ params }: { params: Promise<{ slug: string }> }) {
  const officer = await getOfficerBySlug((await params).slug);
  if (!officer) return <main className="container px-4 py-24 text-center"><h1 className="text-3xl font-black text-primary">Officer profile not found</h1><p className="mt-3 text-muted-foreground">The profile may have moved or is not currently published.</p><Link href="/national-executive" className="mt-8 inline-flex rounded-full bg-primary px-5 py-3 font-bold text-primary-foreground">Back to national executive</Link></main>;
  return <main className="min-h-screen bg-muted/30 px-4 py-8 md:px-6 md:py-14"><div className="container"><Link href="/national-executive" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-ring"><ArrowLeft className="h-4 w-4" />All national officers</Link><article className="overflow-hidden rounded-[2rem] border border-border bg-card shadow-xl"><header className="bg-primary px-6 py-12 text-primary-foreground md:px-12 md:py-16"><p className="mb-4 text-sm font-black uppercase tracking-[0.22em] text-accent">National Executive · Officer Profile</p><h1 className="text-balance text-4xl font-black tracking-tight md:text-6xl">{officer.name}</h1><p className="mt-4 text-xl font-semibold text-primary-foreground/75">{officer.designation}</p></header><div className="grid gap-10 p-6 md:grid-cols-[220px_1fr] md:p-12"><div><div className="h-48 w-48 overflow-hidden rounded-full border-8 border-secondary shadow-lg"><OfficerAvatar name={officer.name} imageUrl={officer.photo_url} /></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">National office bearer of Samta Sainik Dal.</p></div><div className="space-y-8"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-secondary/50 p-5"><MapPin className="mb-3 h-5 w-5 text-ring" /><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">State / zone</p><p className="mt-1 font-bold text-foreground">{officer.state}{officer.zone ? ` · ${officer.zone}` : ""}</p></div><div className="rounded-2xl bg-secondary/50 p-5"><Users className="mb-3 h-5 w-5 text-ring" /><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Sainik under leadership</p><p className="mt-1 font-bold text-foreground">{officer.total_sainik_count ?? 0}</p></div></div>{officer.email && <a href={`mailto:${officer.email}`} className="flex items-center gap-3 font-semibold text-primary hover:text-ring"><Mail className="h-5 w-5 text-ring" />{officer.email}</a>}{officer.bio && <section><h2 className="mb-2 text-2xl font-black text-primary">About</h2><p className="leading-7 text-muted-foreground">{officer.bio}</p></section>}{officer.content_details && <section><h2 className="mb-2 text-2xl font-black text-primary">Responsibilities and work</h2><p className="whitespace-pre-line leading-7 text-muted-foreground">{officer.content_details}</p></section>}<SocialLinks links={officer.social_links} /></div></div></article></div></main>;
}
