import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

const columns = [
  { title:"Organization", links:[["About us","/about"],["Our history","/history"],["Ideology","/about#ideology"],["Structure","/about#structure"]] },
  { title:"Explore", links:[["Articles","/articles"],["Blog","/blog"],["News","/news"],["Events","/events"],["Gallery","/gallery"]] },
  { title:"Get involved", links:[["Become a member","/join"],["Contact","/contact"],["Verify membership","/verify"],["Privacy","/privacy"]] },
];

export function Footer(){ return <footer className="relative overflow-hidden bg-blue-deep text-paper"><div className="container grid gap-12 py-16 md:grid-cols-[1.4fr_2fr] lg:py-20"><div className="max-w-sm"><Link href="/" className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full border border-saffron font-serif text-lg">ॐ</span><span><span className="block font-serif text-2xl">SSD Delhi</span><span className="block text-[10px] uppercase tracking-[.2em] text-saffron">समता सैनिक दल</span></span></Link><p className="mt-6 leading-7 text-paper/65">Soldiers for Equality — building a casteless society through liberty, equality, and fraternity.</p><p className="mt-6 text-sm text-paper/45">Founded by Dr. B.R. Ambedkar in 1924.</p></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{columns.map(column=><nav key={column.title} aria-label={column.title}><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-saffron">{column.title}</h3><ul className="mt-5 flex flex-col gap-3">{column.links.map(([label,href])=><li key={href}><Link href={href} className="text-sm text-paper/65 hover:text-paper">{label}<ArrowUpRight className="ml-1 inline size-3 opacity-0 transition-opacity group-hover:opacity-100" /></Link></li>)}</ul></nav>)}</div></div><div className="container flex flex-col gap-3 border-t border-paper/15 py-6 text-xs text-paper/45 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Samta Sainik Dal Delhi. All rights reserved.</span><span>New Delhi, India · <a href="mailto:info@ssddelhi.org" className="hover:text-paper">info@ssddelhi.org</a></span></div></footer>; }
